runtime: python27
api_version: 1
threadsafe: true

handlers:
    - url: /.*
      static_files: profile-web-app/index.html
      upload: profile-web-app/index.html
    - url: /(.*)
      static_files: ./\1
      upload: ./(.*)
